### ISSUE TITLE
Revise Tab Explanation Interaction

### ISSUE THREAD

**Issue by marota** [mjothy/grid2viz#67]
Beta-testers argued that pop-ups with explanation are a bit frustrating when going from one tab to another.
They suggest to:

- have the explanation text at the top of the Tab page before any data (so that you see it but it is not stopping the navigation, and disappear when you scroll down)
- keep the pop ups when asking for Help

**Comment by vinault** [comment]
We revised the layout of the modal as below in order to put the close button and the Do not show again checkbox at the top. 
The appearance of the modal for brand new users is kept as is and no additional text is added to the views (risk of cluttering).

See 0134a579.

![image](https://user-images.githubusercontent.com/25577263/100622816-9b74ea00-3321-11eb-8e22-4ec551542e40.png)
